# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u9002\u7528\u5e74\u9f84',
                'verbose_name_plural': '\u4ea7\u54c1\u9002\u7528\u5e74\u9f84',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u54c1\u79cd',
                'verbose_name_plural': '\u4ea7\u54c1\u54c1\u79cd',
            },
        ),
        migrations.CreateModel(
            name='RobudProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u4ea7\u54c1\u540d')),
                ('size', models.CharField(max_length=120, null=True, verbose_name='\u7ec4\u88c5\u5c3a\u5bf8')),
                ('pack_size', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u5305\u88c5\u5c3a\u5bf8')),
                ('wood_qty', models.IntegerField(blank=True, null=True, verbose_name='\u6728\u7247\u6570\u91cf')),
                ('age_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robud_website.ApplyAge', verbose_name='\u9002\u7528\u5e74\u9f84')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robud_website.Category', verbose_name='\u6240\u5c5e\u54c1\u79cd')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u4ea7\u54c1',
                'verbose_name_plural': '\u6240\u6709\u4ea7\u54c1',
            },
        ),
    ]
