# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robudproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images/%Y%m%d', verbose_name='\u4ea7\u54c1\u56fe'),
        ),
    ]
