# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0002_robudproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='\u4f5c\u8005')),
                ('age', models.CharField(max_length=120, verbose_name='\u4f5c\u8005\u5e74\u9f84')),
                ('name', models.CharField(max_length=120, verbose_name='\u4f5c\u54c1\u540d\u5b57')),
                ('type', models.CharField(max_length=120, verbose_name='\u4f5c\u54c1\u7c7b\u578b')),
                ('month', models.CharField(max_length=120, verbose_name='\u6708\u4efd')),
            ],
            options={
                'verbose_name': '\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1',
                'verbose_name_plural': '\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1',
            },
        ),
        migrations.CreateModel(
            name='IpSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_number', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u89c6\u9891\u540d\u5b57')),
                ('video', models.FileField(blank=True, upload_to='videos/%Y%m%d', verbose_name='\u89c6\u9891')),
                ('image', models.ImageField(blank=True, upload_to='video_cover/%Y%m%d', verbose_name='\u89c6\u9891\u8868\u5c42\u56fe')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u89c6\u9891',
                'verbose_name_plural': '\u6240\u6709\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u6240\u5c5e\u7c7b\u578b',
                'verbose_name_plural': '\u89c6\u9891\u6240\u5c5e\u7684\u7c7b\u578b\u3001\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='videos',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robud_website.VideoType', verbose_name='\u6240\u5c5e\u54c1\u79cd'),
        ),
        migrations.AddField(
            model_name='customerwork',
            name='like_ips',
            field=models.ManyToManyField(to='robud_website.IpSet', verbose_name='\u70b9\u8d5eip'),
        ),
    ]
