# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0003_auto_20180226_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwork',
            name='image',
            field=models.ImageField(blank=True, upload_to='customer_work/%Y%m%d', verbose_name='\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1'),
        ),
    ]
