# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0004_customerwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwork',
            name='like_ips',
            field=models.ManyToManyField(blank=True, to='robud_website.IpSet', verbose_name='\u70b9\u8d5eip'),
        ),
        migrations.AlterField(
            model_name='robudproduct',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='\u7ec4\u88c5\u5c3a\u5bf8'),
        ),
    ]
