# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0005_auto_20180226_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwork',
            name='month',
            field=models.IntegerField(choices=[(1, '1\u6708'), (2, '2\u6708'), (3, '3\u6708'), (4, '4\u6708'), (5, '5\u6708'), (6, '6\u6708'), (7, '7\u6708'), (8, '8\u6708'), (9, '9\u6708'), (10, '10\u6708'), (11, '11\u6708'), (12, '12\u6708')], max_length=120, verbose_name='\u6708\u4efd'),
        ),
    ]
