# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0006_auto_20180226_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1\u7c7b\u578b',
                'verbose_name_plural': '\u5c0f\u827a\u672f\u5bb6\u4f5c\u54c1\u7c7b\u578b',
            },
        ),
        migrations.RemoveField(
            model_name='customerwork',
            name='type',
        ),
        migrations.AddField(
            model_name='customerwork',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robud_website.CustomerWorkType', verbose_name='\u4f5c\u54c1\u7c7b\u578b'),
        ),
    ]
