# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robud_website', '0008_auto_20180226_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': '\u4e8c\u7ea7\u6807\u9898',
                'verbose_name_plural': '\u4e8c\u7ea7\u6807\u9898',
            },
        ),
        migrations.AddField(
            model_name='robudproduct',
            name='title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robud_website.SecondTitle', verbose_name='\u4e8c\u7ea7\u6807\u9898'),
        ),
    ]
